/**
 * Controlled vocabulary of clinical findings the extraction layer can emit.
 * Rule criteria resolve against these concept IDs deterministically —
 * the LLM only reports whether a concept was stated present/absent.
 */
export const CONCEPT_IDS = [
  // Malignancy / oncology context
  "active_malignancy",
  "solid_tumor",
  "recent_cytotoxic_chemotherapy",
  "checkpoint_inhibitor_therapy",
  "known_neutropenia",
  "prior_fungal_infection",
  // Thromboembolism
  "hemoptysis",
  "pleuritic_chest_pain",
  "dyspnea",
  "dvt_signs",
  "unilateral_leg_swelling",
  "entire_leg_swelling",
  "calf_swelling_gt_3cm",
  "deep_vein_tenderness",
  "unilateral_pitting_edema",
  "collateral_superficial_veins",
  "leg_paralysis_or_immobilization",
  "recent_surgery_or_trauma",
  "bedridden_or_immobilized",
  "prior_vte",
  "estrogen_use",
  // Infection / sepsis
  "fever",
  "rigors",
  "altered_mental_status",
  "hypotension",
  "copd",
  "dehydration",
  "outpatient_at_fever_onset",
  "severe_symptom_burden",
  "poor_performance_status",
  "chronic_cardiovascular_disease",
  "mucositis_grade_2_or_higher",
  "stress_hyperglycemia",
  // Cardiac
  "chest_pain",
  "smoking",
  "diabetes",
  "hypertension",
  "hyperlipidemia",
  "obesity",
  "family_history_early_cad",
  "known_cad_or_atherosclerosis",
  "ecg_ischemic_changes",
  "troponin_elevated",
  // Neuro / oncologic emergencies
  "back_pain",
  "lower_extremity_weakness",
  "bladder_or_bowel_dysfunction",
  "saddle_anesthesia",
  "focal_neurologic_deficit",
  "headache",
  // GI
  "diarrhea",
  "abdominal_pain",
] as const;

export type ConceptId = (typeof CONCEPT_IDS)[number];

export const CONCEPT_LABELS: Record<ConceptId, string> = {
  active_malignancy: "Active malignancy",
  solid_tumor: "Solid tumor",
  recent_cytotoxic_chemotherapy: "Recent cytotoxic chemotherapy",
  checkpoint_inhibitor_therapy: "Checkpoint inhibitor therapy",
  known_neutropenia: "Known neutropenia",
  prior_fungal_infection: "Prior fungal infection",
  hemoptysis: "Hemoptysis",
  pleuritic_chest_pain: "Pleuritic chest pain",
  dyspnea: "Dyspnea",
  dvt_signs: "Clinical signs of DVT",
  unilateral_leg_swelling: "Unilateral leg swelling",
  entire_leg_swelling: "Entire leg swollen",
  calf_swelling_gt_3cm: "Calf swelling >3 cm vs other side",
  deep_vein_tenderness: "Tenderness along deep venous system",
  unilateral_pitting_edema: "Pitting edema (symptomatic leg)",
  collateral_superficial_veins: "Collateral superficial veins",
  leg_paralysis_or_immobilization: "Paralysis/paresis or recent leg immobilization",
  recent_surgery_or_trauma: "Recent surgery or trauma (≤4 weeks)",
  bedridden_or_immobilized: "Bedridden ≥3 days or major surgery ≤12 weeks",
  prior_vte: "Previous PE or DVT",
  estrogen_use: "Estrogen / hormone use",
  fever: "Fever (reported)",
  rigors: "Rigors / chills",
  altered_mental_status: "Altered mental status / confusion",
  hypotension: "Hypotension (reported)",
  copd: "COPD",
  dehydration: "Dehydration",
  outpatient_at_fever_onset: "Outpatient at fever onset",
  severe_symptom_burden: "Severe symptom burden",
  poor_performance_status: "ECOG performance status ≥2 (not fully ambulatory)",
  chronic_cardiovascular_disease: "Chronic cardiovascular disease",
  mucositis_grade_2_or_higher: "Mucositis grade ≥2 (NCI-CTCAE)",
  stress_hyperglycemia: "Stress-induced hyperglycemia",
  chest_pain: "Chest pain / pressure",
  smoking: "Current or recent smoking",
  diabetes: "Diabetes mellitus",
  hypertension: "Hypertension",
  hyperlipidemia: "Hyperlipidemia",
  obesity: "Obesity (BMI >30)",
  family_history_early_cad: "Family history of early CAD",
  known_cad_or_atherosclerosis: "Known CAD or atherosclerotic disease",
  ecg_ischemic_changes: "Ischemic ECG changes",
  troponin_elevated: "Elevated troponin",
  back_pain: "Back pain",
  lower_extremity_weakness: "Lower-extremity weakness",
  bladder_or_bowel_dysfunction: "Bladder or bowel dysfunction",
  saddle_anesthesia: "Saddle anesthesia",
  focal_neurologic_deficit: "Focal neurologic deficit",
  headache: "Headache",
  diarrhea: "Diarrhea",
  abdominal_pain: "Abdominal pain",
};

export const LAB_NAMES = [
  "wbc",
  "anc",
  "hemoglobin",
  "platelets",
  "sodium",
  "potassium",
  "bun",
  "creatinine",
  "calcium",
  "albumin",
  "lactate",
  "troponin",
  "glucose",
  "crp",
  "monocytes",
] as const;

export type LabName = (typeof LAB_NAMES)[number];

export const LAB_LABELS: Record<LabName, string> = {
  wbc: "WBC (×10⁹/L)",
  anc: "ANC (×10⁹/L)",
  hemoglobin: "Hemoglobin (g/dL)",
  platelets: "Platelets (×10⁹/L)",
  sodium: "Sodium (mmol/L)",
  potassium: "Potassium (mmol/L)",
  bun: "BUN (mg/dL)",
  creatinine: "Creatinine (mg/dL)",
  calcium: "Calcium (mg/dL)",
  albumin: "Albumin (g/dL)",
  lactate: "Lactate (mmol/L)",
  troponin: "Troponin (ng/L)",
  glucose: "Glucose (mg/dL)",
  crp: "CRP (mg/L)",
  monocytes: "Monocytes (/mm³)",
};
