import type { PatientContext } from "./patient";
import type { ConcernView } from "./api-types";
import demoResults from "./fixtures/demo-results.json";

/**
 * Precomputed safety-check results for the synthetic demo cases, keyed by
 * demo case id. Generated by `scripts/generate-fixtures.ts` against the live
 * pipeline — commit the JSON, don't hand-edit it.
 *
 * Selecting an unedited demo case renders from here instantly, with no
 * network call. Any edit to the presentation or structured fields (or
 * free-text input) always goes through the live streaming API — see
 * `isEditedFromFixture` in page.tsx for the exact rule.
 */
export interface DemoFixtureResult {
  patient: PatientContext;
  concerns: ConcernView[];
  usedMockProvider: boolean;
}

export const DEMO_FIXTURES = demoResults as unknown as Partial<
  Record<string, DemoFixtureResult>
>;
